### ISSUE TITLE
不好意思打扰了 问一下关于书签制作相关

### ISSUE THREAD

**Issue by gabuly** [TkzcM/expanda#3]
对代码这些一无所知。虽然我自己有账号，但是可以的话我希望如果现在的书签挂掉我可以为制作新的付费。所以想问下做一个这样的书签的成本是啥  谢谢

**Comment by TkzcM** [comment]
https://expanda.now.sh/
有账号用这个就好了

**Comment by gabuly** [comment]
哦哦 谢谢
